# railway.toml
[build]
builder = "DOCKERFILE"

[services.backend]
root = "backend"
dockerfile = "backend/Dockerfile"
autoDeploy = true
startCommand = "npm start"

[services.frontend]
root = "frontend"
dockerfile = "frontend/Dockerfile"
autoDeploy = true
startCommand = "serve -s build -l $PORT"
