# Configuração de múltiplos serviços

[backend]
root = "backend"
start = "npm start"

[frontend]
root = "frontend"
start = "npm run start"

[build]
builder = "dockerfile"

[deploy]
startCommand = "sh ./start.sh"
